sudo: false
language: c
addons:
  apt:
    packages:
      - protobuf-compiler
      - libprotobuf-dev
      - python-protobuf

script:
  - ls -l /usr/include/google/protobuf/descriptor.proto
  - make all
